mode = "dark"
accent = "#ec934b"
selection = "#343434"
selection_foreground = "#ffe3ae"
selection_background = "#343434"
muted = "#969087"
background = "#141414"
dark_background = "#0e0e0e"
darker_background = "#090909"
lighter_background = "#272727"
foreground = "#edc080"
dark_foreground = "#ab997b"
light_foreground = "#d9b98b"
bright_foreground = "#ffe3ae"
red = "#ef8063"
yellow = "#e9c66d"
orange = "#ec934b"
green = "#7e9f64"
cyan = "#77947d"
blue = "#9caaa0"
magenta = "#d7a17c"
brown = "#b08c63"
bright_red = "#ffa080"
bright_yellow = "#ffdb88"
bright_green = "#97b57b"
bright_cyan = "#94ae98"
bright_blue = "#bec6bd"
bright_magenta = "#efbc98"
hyprland_active_border = "rgba(ffd58aff) rgba(c59659ff) 45deg"
hyprland_inactive_border = "rgba(63513bff)"
